# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        # Required to make flake8 read from pyproject.toml for now :(
        additional_dependencies: ["flake8-pyproject"]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        language_version: "3.10"
  - repo: https://github.com/wazo-platform/wazo-git-hooks
    rev: 1.1.4
    hooks:
      - id: wazo-copyright-check